version: '3.8'
services:
  serv1:
    build: ./service1
    ports:
      - 3000:3000
  serv2:
    build: ./service2
    ports:
      - 3001:3000
  serv3:
    build: ./service3
    ports:
      - 3002:3000
  gateway:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf